export enum PREFIX {
  ADDRESS = "addr",
  BRAND = "brand",
  CITY = "city",
  MATERIAL = "material",
  MC_SHOW_REVIEW = "mc_show_rev",
  MC = "mc",
  OPERATOR = "opr",
  PLATFORM = "platform",
  SHOW_REVIEW = "show_rev",
  SHOW = "show",
  STUDIO = "studio",
  STUDIO_ROOM = "std_room",
  TASK = "task",
  USER = "usr",
}
