export enum PREFIX {
  ADDRESS = "addr",
  CLIENT = "client",
  CITY = "city",
  FORM_TEMPLATE = "form_tpl",
  MATERIAL = "material",
  MC = "mc",
  MEMBER = "member",
  PLATFORM = "platform",
  SHOW_MC = "show_mc",
  SHOW_MC_MATERIAL = "show_mc_mat",
  SHOW_PLATFORM = "show_plat",
  SHOW = "show",
  STUDIO = "studio",
  STUDIO_ROOM = "std_room",
  TASK = "task",
}
